package com.humansarehuman.blue2factor.dataAndAccess;

import com.humansarehuman.blue2factor.utilities.Logging;

@SuppressWarnings("all")
class DeviceFields { // NO_UCD (use default)
	protected Logging logger = new Logging(this.getClass());

	final String accessCodeFields = "CREATE_DATE, ACCESS_CODE, SERVER_ID, DEVICE_ID, PERMISSIONS, ACTIVE, "
			+ "BROWSER_ID";

	final String browserFields = "DEVICE_ID, BROWSER_ID, CREATE_DATE, EXPIRE_DATE, LAST_UPDATE, DESCRIPTION, HAS_FAILED";

	final String tokenFields = "GROUP_ID, DEVICE_ID, TOKEN_ID, "
			+ "AUTHORIZATION_TIME, EXPIRE_TIME, LAST_CHECK, LAST_UPDATE, DESCRIPTION, NEEDS_UPDATE, BROWSER_ID, "
			+ "PERMISSION, BASE_URL";

	final String connectionFields = "CREATE_DATE, CONNECTION_ID, PERIPHERAL_DEVICE_ID, CENTRAL_DEVICE_ID, "
			+ "SERVICE_UUID, CHARACTER_UUID, GROUP_ID, ACTIVE, LAST_CHECK, LAST_SUCCESS, "
			+ "ADVERTISING_PERIPHERAL, CONNECTING_CENTRAL, SUBSCRIBED, INSTALL_COMPLETE, "
			+ "PERIPHERAL_CONNECTED, LAST_PERIPHERAL_CONNECTION_SUCCESS,"
			+ "CENTRAL_CONNECTED, LAST_CENTRAL_CONNECTION_SUCCESS, PERIPHERAL_RSSI, CENTRAL_RSSI, "
			+ "PERIPHERAL_RSSI_TIMESTAMP, CENTRAL_RSSI_TIMESTAMP";

	final String deviceFields = "GROUP_ID, USER_ID, DEVICE_ID, SEED, ACTIVE, "
			+ "FCM_ID, BT_ADDRESS, CREATE_DATE, LAST_UPDATE, DEVICE_TYPE, OPERATING_SYSTEM, "
			+ "LOGIN_TOKEN, LAST_COMPLETE_CHECK, OS_VERSION, "
			+ "USER_LANGUAGE, LAST_GMT_OFFSET, SCREEN_SIZE, RAND, SHOW_ICON, "
			+ "DEVICE_PRIORITY, TRIGGER_UPDATE, RECENT_PUSHES, UNRESPONSIVE, "
			+ "LAST_PUSH, PUSH_LOUD, PUSH_FAILURE, COMMAND, "
			+ "TEMP, CENTRAL, LAST_RESET, SCREENSAVER_ON, LAST_VARIABLE_RETRIEVAL, TURNED_OFF, DEVICE_CLASS, "
			+ "BROWSER_INSTALL_COMPLETE, SIGNED_IN, LAST_SILENT_PUSH, LAST_SILENT_PUSH_RESPONSE, "
			+ "HAS_BLE, TURN_OFF_FROM_INSTALLER, PHONE_NUMBER," + "MULTI_USER, PASSKEY_ENABLED, TX_POWER, "
			+ "TERMINATE";

	final String checkFields = "CHECK_ID, INSTANCE_ID, CENTRAL_DEVICE_ID, PERIPHERAL_DEVICE_ID, "
			+ "SERVICE_UUID, USER_ID, CENTRAL_BSSID, CENTRAL_SSID, PERIPHERAL_BSSID,"
			+ "PERIPHERAL_SSID, EXPIRED, COMPLETED, "
			+ "OUTCOME, CREATE_DATE, COMPLETION_DATE, VERIFIED_RECEIPT, CHECK_TYPE, "
			+ "CENTRAL_INSTANCE_ID, PERIPHERAL_INSTANCE_ID, EXPIRATION_DATE";

	final String groupFields = "COMPANY_ID, GROUP_ID, GROUP_NAME, ACTIVE, ACCEPTED_TYPES, "
			+ "CREATE_DATE, TIMEOUT_SECS, GROUP_PW, SALT, DEVICES_ALLOWED, DEVICES_IN_USE, "
			+ "PERMISSIONS, USERNAME, TOKEN_DATE, UID, USER_TYPE, USER_EXEMPT, PUSH_ALLOWED, TEXT_ALLOWED";

	final String companyFields = "COMPANY_ID, COMPANY_NAME, ACTIVE, COMPANY_SECRET, ACCEPTED_TYPES, "
			+ "CREATE_DATE, COMPANY_LOGIN_TOKEN, COMPANY_COMPLETION_URL, API_KEY, LICENSE_COUNT, "
			+ "LICENSES_IN_USE, COMPANY_BASE_URL, COMPANY_LOGIN_URL, "
			+ "F1_METHOD, F2_METHOD, LOGOUT_URL, URL_REGEX, NON_MEMBER_STRATEGY, PUSH_ALLOWED, "
			+ "TEXT_ALLOWED, PUSH_TIMEOUT_SECONDS, TEXT_TIMEOUT_SECONDS, PASSKEY_TIMEOUT_SECONDS, "
			+ "ALLOW_ALL_FROM_IDP, MOVE_B2F_USERS_TO_IDP, EMAIL_DOMAIN, ADMIN_CODE_TIMEOUT_SECONDS, ENTITY_ID_VAL";

	final String ldapServerFields = "TABLE_ID, COMPANY_ID, CREATE_DATE, ACTIVE, PROVIDER_URL, SEARCH_BASE, JKS_FILE, "
			+ "JKS_PASSWORD, SERVICE_USERNAME, SERVICE_PASSWORD";

	final String brandingFields = "COMPANY_ID, ICON_PATH, BACKGROUND_COLOR, FOREGROUND_COLOR, TITLE_IMAGE_PATH";

	final String logFields = "CREATE_DATE, DEVICE_ID, SRC, TXT, LEVEL, ENV";

	final String authFields = "USER_ID, AUTHORIZATION_TIME, AUTHORIZATION_COMPLETED, REQUESTING_DEVICE, "
			+ "CENTRAL_DEVICE";

	final String serverFields = "CREATE_DATE, SERVER_ID, B2F_ID, PERMISSIONS, ACTIVE, ENABLED, SERVER_NAME, "
			+ "COMPANY_ID, HOSTNAME, DESCRIPTION";

	final String serverConnectionFields = "CREATE_DATE, SERVER_ID, GROUP_ID, PERMISSIONS, ACTIVE";

	@SuppressWarnings("ucd")
	final String authenticatorFields = "CRED_ID, BROWSER_ID, TYPE, SIGN_COUNT, ATTESTED_CREDENTIAL_DATA, "
			+ "ATTESTATION_OBJECT, COLLECTED_CLIENT_DATA, FORMAT, CREATE_DATE, EXPIRED";

	final static String companyGroupDeviceFields = "company.ACCEPTED_TYPES AS company_ACCEPTED_TYPES,"
			+ "company.ACTIVE AS company_ACTIVE," + "company.ALLOW_ALL_FROM_IDP AS company_ALLOW_ALL_FROM_IDP,"
			+ "company.API_KEY AS company_API_KEY," + "company.COMPANY_BASE_URL AS company_COMPANY_BASE_URL,"
			+ "company.COMPANY_COMPLETION_URL AS company_COMPANY_COMPLETION_URL,"
			+ "company.COMPANY_ID AS company_COMPANY_ID,"
			+ "company.COMPANY_LOGIN_TOKEN AS company_COMPANY_LOGIN_TOKEN,"
			+ "company.COMPANY_LOGIN_URL AS company_COMPANY_LOGIN_URL,"
			+ "company.COMPANY_NAME AS company_COMPANY_NAME,"
			+ "company.COMPANY_PUBLIC_KEY AS company_COMPANY_PUBLIC_KEY,"
			+ "company.COMPANY_SECRET AS company_COMPANY_SECRET," + "company.CREATE_DATE AS company_CREATE_DATE,"
			+ "company.EMAIL_DOMAIN AS company_EMAIL_DOMAIN," + "company.F1_METHOD AS company_F1_METHOD,"
			+ "company.F2_METHOD AS company_F2_METHOD," + "company.LICENSE_COUNT AS company_LICENSE_COUNT,"
			+ "company.LICENSES_IN_USE AS company_LICENSES_IN_USE," + "company.LOGOUT_URL AS company_LOGOUT_URL,"
			+ "company.MOVE_B2F_USERS_TO_IDP AS company_MOVE_B2F_USERS_TO_IDP,"
			+ "company.NON_MEMBER_STRATEGY AS company_NON_MEMBER_STRATEGY,"
			+ "company.PASSKEY_TIMEOUT_SECONDS AS company_PASSKEY_TIMEOUT_SECONDS,"
			+ "company.PUSH_ALLOWED AS company_PUSH_ALLOWED,"
			+ "company.PUSH_TIMEOUT_SECONDS AS company_PUSH_TIMEOUT_SECONDS,"
			+ "company.TEXT_ALLOWED AS company_TEXT_ALLOWED,"
			+ "company.TEXT_TIMEOUT_SECONDS AS company_TEXT_TIMEOUT_SECONDS,"
			+ "company.ADMIN_CODE_TIMEOUT_SECONDS AS company_ADMIN_CODE_TIMEOUT_SECONDS,"
			+ "company.URL_REGEX AS company_URL_REGEX," + "company.ENTITY_ID_VAL AS company_COMPANY_ID_VAL, "
			+ "grp.ACCEPTED_TYPES AS grp_ACCEPTED_TYPES," + "grp.ACTIVE AS grp_ACTIVE,"
			+ "grp.COMPANY_ID AS grp_COMPANY_ID," + "grp.CREATE_DATE AS grp_CREATE_DATE,"
			+ "grp.DEVICES_ALLOWED AS grp_DEVICES_ALLOWED," + "grp.DEVICES_IN_USE AS grp_DEVICES_IN_USE,"
			+ "grp.GROUP_ID AS grp_GROUP_ID," + "grp.GROUP_NAME AS grp_GROUP_NAME," + "grp.GROUP_PW AS grp_GROUP_PW,"
			+ "grp.PERMISSIONS AS grp_PERMISSIONS," + "grp.PUSH_ALLOWED AS grp_PUSH_ALLOWED," + "grp.SALT AS grp_SALT,"
			+ "grp.TEMP AS grp_TEMP," + "grp.TEXT_ALLOWED AS grp_TEXT_ALLOWED,"
			+ "grp.TIMEOUT_SECS AS grp_TIMEOUT_SECS," + "grp.TOKEN_DATE AS grp_TOKEN_DATE," + "grp.UID AS grp_UID,"
			+ "grp.USER_EXEMPT AS grp_USER_EXEMPT," + "grp.USER_TYPE AS grp_USER_TYPE,"
			+ "grp.USERNAME AS grp_USERNAME, " + "device.ACTIVE AS device_ACTIVE,"
			+ "device.BROWSER_INSTALL_COMPLETE AS device_BROWSER_INSTALL_COMPLETE,"
			+ "device.BT_ADDRESS AS device_BT_ADDRESS," + "device.CENTRAL AS device_CENTRAL,"
			+ "device.COMMAND AS device_COMMAND," + "device.CREATE_DATE AS device_CREATE_DATE,"
			+ "device.DEVICE_CLASS AS device_DEVICE_CLASS," + "device.DEVICE_ID AS device_DEVICE_ID,"
			+ "device.DEVICE_PRIORITY AS device_DEVICE_PRIORITY," + "device.DEVICE_TYPE AS device_DEVICE_TYPE,"
			+ "device.FCM_ID AS device_FCM_ID," + "device.GROUP_ID AS device_GROUP_ID,"
			+ "device.HAS_BLE AS device_HAS_BLE," + "device.LAST_COMPLETE_CHECK AS device_LAST_COMPLETE_CHECK,"
			+ "device.LAST_GMT_OFFSET AS device_LAST_GMT_OFFSET," + "device.LAST_PUSH AS device_LAST_PUSH,"
			+ "device.LAST_RESET AS device_LAST_RESET," + "device.LAST_SILENT_PUSH AS device_LAST_SILENT_PUSH,"
			+ "device.LAST_SILENT_PUSH_RESPONSE AS device_LAST_SILENT_PUSH_RESPONSE,"
			+ "device.LAST_UPDATE AS device_LAST_UPDATE,"
			+ "device.LAST_VARIABLE_RETRIEVAL AS device_LAST_VARIABLE_RETRIEVAL,"
			+ "device.LOGIN_TOKEN AS device_LOGIN_TOKEN," + "device.MULTI_USER AS device_MULTI_USER,"
			+ "device.OPERATING_SYSTEM AS device_OPERATING_SYSTEM," + "device.OS_VERSION AS device_OS_VERSION,"
			+ "device.PASSKEY_ENABLED AS device_PASSKEY_ENABLED," + "device.PHONE_NUMBER AS device_PHONE_NUMBER,"
			+ "device.PUSH_FAILURE AS device_PUSH_FAILURE," + "device.PUSH_LOUD AS device_PUSH_LOUD,"
			+ "device.RAND AS device_RAND," + "device.RECENT_PUSHES AS device_RECENT_PUSHES,"
			+ "device.SCREEN_SIZE AS device_SCREEN_SIZE," + "device.SCREENSAVER_ON AS device_SCREENSAVER_ON,"
			+ "device.SEED AS device_SEED," + "device.SHOW_ICON AS device_SHOW_ICON,"
			+ "device.SIGNED_IN AS device_SIGNED_IN," + "device.TEMP AS device_TEMP,"
			+ "device.TRIGGER_UPDATE AS device_TRIGGER_UPDATE," + "device.TX_POWER AS device_TX_POWER,"
			+ "device.TURN_OFF_FROM_INSTALLER AS device_TURN_OFF_FROM_INSTALLER,"
			+ "device.TURNED_OFF AS device_TURNED_OFF," + "device.UNRESPONSIVE AS device_UNRESPONSIVE,"
			+ "device.USER_ID AS device_USER_ID," + "device.USER_LANGUAGE AS device_USER_LANGUAGE"
			+ "device.TERMINATE AS device_TERMINATE";
}
