<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="spring" uri="/WEB-INF/tld/spring.tld"  %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <%@ include file="header.jsp" %>
</head>
<body>
    <input type='hidden' id='publicKey' value='${ publicKey }'>
    <input type='hidden' id='noDevicesRegistered' value='${ noDevicesRegistered }'>
    <div id="banner">
    	<a href="/settings"><span class="users">Settings</span></a>
        <a href="/servers"><span class="users">Servers</span></a>
        <a href="/serviceProviders"><span class="users">Service Providers</span></a>
        <a href="/company"><span class="users">Users</span></a>
        <a href="#" id='signOutClick'><span class="users">Sign Out</span></a>
    </div>
    <div id="mobileBanner"><img id="mobileMenu" src="/imgFiles/white_hamburger.png" alt="menu button"></div>
    <div id="fullBody">
        <%@ include file="sidePanel.jsp" %>
        <div id="centerPanel">
            <div id="message" class='redMessage'>${ errorMessage }</div>
            <img id="licenseLogo" src="/imgFiles/b2f96.png" alt="NearAuth.ai logo">
            <div class='installText'>
                <div class='installInstructions'>
                    <div class='installSubtitle'>7 Steps to Protection</div>
                    <div class='stepNumber'>Step 1</div>
                    <div class='stepText'>If you haven't done so already, register for NearAuth.ai <a href='/signup' 
                        class='underline'>here</a>.</div>
            
                    <div class='stepNumber'>Step 2</div>
                    <div class='stepText'>Retrieve the email we sent you when you registered, 
                    and proceed to the registration link.</div>
            
                    <div class='stepNumber'>Step 3</div>
                    <div class='stepText'>Click the Upload SAML Data button and paste your Identity Provider's 
                    SAML metadata in the text box.</div>
            
                    <div class='stepNumber'>Step 4</div>
                    <div class='stepText'>Click the Set Internal URL button and enter your company's internal landing page.</div>
    
            
                    <div class='stepNumber'>Step 5</div>
                    <div class='stepText'>Create a public/private RSA key pair in PEM format. Using OpenSSL,
                        the keys can be generated by first running:
                    <div class='code2'>openssl genrsa -out key.pem 2048</div>
                    to generate the private key, and then running
                    <div class='code2'>openssl rsa -in key.pem -outform PEM -pubout -out public.pem</div>
                    to get the public key.<br><br>Once you have created the keys, upload the text of the public key by clicking the
                    Upload Web Server Public Key button.  Paste the text of your public key into the box.<br><br>The private key will be used by your web backend.</div>
    
            
                    <div class='stepNumber'>Step 6</div>
                    <div class='stepText'>Upload the values below to your identity provider. Your company Id
                    can be found at the left.
                    </div>
                    <div class='code3'>Entity ID = ${secureUrl }/SAML2/SSO/{COMPANY_ID}/EntityId</div>
                    <div class='code3'>Reply URL = ${secureUrl }/SAML2/SSO/{COMPANY_ID}/fromIdp</div>
                    <div class='code3'>Signin URL = ${secureUrl }/SAML2/SSO/{COMPANY_ID}/SignIn</div>
                    <div class='code3'>Logout URL = ${secureUrl }/logout</div>
            
                    <div class='stepNumber'>Step 7</div>
                    <div class='stepText'>Download the code package for your backend language and set up 
                    the hooks. The hooks are the incoming request, the CompanyID and Internal URL from 
                    your NearAuth.ai Company Page, and the private key you created in Step 5.</div>
                    <div class='stepNumber'>Packages</div>
                    <div class='csLang'>Java via Maven:</div>
                    <div class='code3'>&lt;dependency&gt;&#10;
                    <br>&nbsp;&nbsp; &nbsp;&lt;groupId&gt;com.blue2factor.authentication&lt;/groupId&gt;&#10;
                    <br>&nbsp;&nbsp; &nbsp;&lt;artifactId&gt;java-b2f&lt;/artifactId&gt;&#10;
                    <br>&nbsp;&nbsp; &nbsp;&lt;version&gt;1.0-SNAPSHOT&lt;/version&gt;&#10;
                    <br>&lt;/dependency&gt;<br></div>
                    <div class='codeLink'>Or at <a href='https://github.com/bk89686/JavaB2f' class='underline'>https://github.com/bk89686/JavaB2f</a></div>
                    <div class='csLang'>Node.js via npm</div>
                    <div class='code3'>npm install blue2factor</div>
                    <div class='codeLink'>Or at <a href='https://github.com/bk89686/NodeB2f' class='underline'>https://github.com/bk89686/NodeB2f</a></div>
                    <div class='csLang'>php via composer</div>
                    <div class='code3'>composer require blue2factor/authentication</div>
                    <div class='codeLink'>Or at <a href='https://github.com/bk89686/PhpB2f' class='underline'>https://github.com/bk89686/PhpB2f</a></div>
                    <div class='csLang'>Python via pip</div>
                    <div class='code3'>python3 -m pip install Blue2FactorPy==0.1.3</div>
                    <div class='codeLink'>Or at <a href='https://github.com/bk89686/PyB2f' class='underline'>https://github.com/bk89686/PyB2f</a></div>
                    <div class='stepText'>If any of this sounds imposing,
                    please email (help@NearAuth.ai) or call us (607-238-3533) and we can either walk you 
                    through it, or perform the installation for you.<br><br>
                    Similarly, if you need a different backend language, let us know.</div>
            
                    <div class='stepNumber'>Step 8</div>
                    <div class='stepText'>Signup your first devices using your phone and your computer.</div>
                    <div class='stepText'>Directions can be found <a href='https://www.NearAuth.ai/signupDevices' class='underline'>here</a>.
                    <div class='bottomPadding'></div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div id='mobileMenuText'>
        <div id='mobileMenuDocumentation'><a href="${secureUrl }/company" class="noUnderline black">Admin</a></div>
        <div id='mobileMenuSignOut'>Sign Out</div>
    </div>
    
    <input type='hidden' id='b2fIgnorePageFlag' value='true'></input>
    <%@ include file="popup.jsp" %>
    <%@ include file="footerClient.jsp" %>
</body>
</html>
